Controllers/CreateOrderController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SanTech.Interfaces;
using SanTech.Models;

namespace SanTech.Controllers
{
    public class CreateOrderController : Controller
    {
        private readonly IDbUserService _dbUserService;
        private readonly IDbBasketService _dbBasketService;
        private readonly IEmailService _emailService;
        private readonly IOrderService _orderService;
        public CreateOrderController(IDbUserService dbUserService, IDbBasketService dbBasketService, IEmailService emailService, IOrderService orderService)
        {
            _dbUserService = dbUserService;
            _dbBasketService = dbBasketService;
            _emailService = emailService;
            _orderService = orderService;
        }

        [HttpGet]
        public IActionResult CreateOrder()
        {
            var userEmail = HttpContext.Session.GetString("Email");
            if (userEmail is not null)
            {
                if (_dbUserService.Get(userEmail).Basket.Count() != 0)
                {
                    ViewBag.BasketCost = _dbBasketService.Get(userEmail).Sum(x => x.NumberOfProduct * (x.Product.Cost * (100 - x.Product.SaleProcent) / 100));
                    ViewBag.User = _dbUserService.Get(userEmail);
                    return View();
                }
            }

            return Redirect("../Home/Index");
        }

        [HttpPost]
        public IActionResult CreateOrder(OrderViewModel order)
        {
            var userEmail = HttpContext.Session.GetString("Email");
            ViewBag.User = _dbUserService.Get(userEmail);
            ViewBag.BasketCost = _dbBasketService.Get(userEmail).Sum(x => x.NumberOfProduct * (x.Product.Cost * (100 - x.Product.SaleProcent) / 100));
            if (ModelState.IsValid)
            {
                order.Basket = _dbBasketService.Get(userEmail);
                order.User = _dbUserService.Get(userEmail);
                order.TotalCost = order.Basket.Sum(x => x.NumberOfProduct * (x.Product.Cost * (100 - x.Product.SaleProcent) / 100));
                _orderService.Add(order);
                _emailService.SendCheckToEmail(order);
                _dbBasketService.DeleteAll(userEmail);
                return View("../CreateOrder/Created", order);
            }

            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SanTech.Interfaces;
using SanTech.Models;
using SanTech.Models.ViewModels;

namespace SanTech.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDbUserService _dbUserService;
        private readonly IDbProductService _dbProductService;
        private readonly IDbBasketService _dbBasketService;
        private readonly IDbFavoriteService _dbFavoriteService;
        public HomeController(IDbUserService dbUserService, IDbProductService dbProductService, IDbBasketService dbBasketService, IDbFavoriteService dbFavoriteService)
        {
            _dbUserService = dbUserService;
            _dbProductService = dbProductService;
            _dbBasketService = dbBasketService;
            _dbFavoriteService = dbFavoriteService;
        }

        public IActionResult Index(SearchViewModel search)
        {
            var userEmail = HttpContext.Session.GetString("Email");
            // ViewBag.LoggedAccount = userEmail;
            if (userEmail is not null)
            {
                ViewBag.User = _dbUserService.Get(userEmail);
            }

            var allProducts = _dbProductService.GetAll();
            var products = _dbProductService.GetProductsInRange(0, 20, _dbProductService.Get(search)).ToList();
            if (allProducts.Count() > 0)
            {
                ViewBag.MaxCost = _dbProductService.GetAll().Max(x => (x.Cost * (100 - x.SaleProcent) / 100));
            }

            ViewBag.Search = search;
            return View(products);
        }

        public string SignOutAccount()
        {
            ControllerContext.HttpContext.Session.Remove("Email");
            return "<li><a href='../SignInAccount/SignInAccount'><div class='text1 pull__menu__list__text login__button'>Вход/Регистрация</div></a></li>";
        }

        [HttpPost]
        public ViewResult GetAdditionalProducts(int from, int count, SearchViewModel search)
        {
            var userEmail = HttpContext.Session.GetString("Email");
            if (userEmail is not null)
            {
                ViewBag.User = _dbUserService.Get(userEmail);
            }
            var products = _dbProductService.GetProductsInRange(from, count, _dbProductService.Get(search)).ToList();
            return View(products);
        }

        public bool AddToBasket(int id)
        {
            var userEmail = HttpContext.Session.GetString("Email");
            return _dbBasketService.Add(userEmail, id);
        }

        public bool AddToFavourites(int id)
        {
            var userEmail = HttpContext.Session.GetString("Email");
            return _dbFavoriteService.Add(userEmail, id);
        }

        public void DeleteFromBasket(int basketId)
        {
            _dbBasketService.Delete(basketId);
        }

        public void DeleteFromFavorites(int favoriteId)
        {
            _dbFavoriteService.Delete(favoriteId);
        }

        public ViewResult LoadBasket()
        {
            var userEmail = HttpContext.Session.GetString("Email");
            ViewBag.User = userEmail;
            var model = _dbBasketService.Get(userEmail);
            ViewBag.TotalCost = model.Sum(x => x.NumberOfProduct * (x.Product.Cost * (100 - x.Product.SaleProcent) / 100));
            return View(model);
        }

        public ViewResult LoadFavorites()
        {
            var userEmail = HttpContext.Session.GetString("Email");
            ViewBag.User = userEmail;
            var model = _dbFavoriteService.Get(userEmail);
            return View(model);
        }

        public void ChangeNumberOfBasket(int basketId, int inputValue)
        {
            _dbBasketService.ChangeNumberOfBasket(basketId, inputValue);
        }

        public void DeleteAllBasket()
        {
            var userEmail = HttpContext.Session.GetString("Email");
            _dbBasketService.DeleteAll(userEmail);
        }

        public void DeleteAllFavorites()
        {
            var userEmail = HttpContext.Session.GetString("Email");
            _dbFavoriteService.DeleteAll(userEmail);
        }

        [HttpGet]
        public IActionResult UpdateUser()
        {
            var userEmail = HttpContext.Session.GetString("Email");
            if (userEmail is not null)
            {
                ViewBag.User = _dbUserService.Get(userEmail);
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult UpdateUser(User user, IFormFile uploadedFile)
        {
            var userEmail = HttpContext.Session.GetString("Email");
            _dbUserService.UpdateUser(user, userEmail, uploadedFile);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ViewProductController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SanTech.Interfaces;

namespace SanTech.Controllers
{
    public class ViewProductController : Controller
    {
        private readonly IDbUserService _dbUserService;
        private readonly IDbProductService _dbProductService;
        public ViewProductController(IDbUserService dbUserService, IDbProductService dbProductService)
        {
            _dbUserService = dbUserService;
            _dbProductService = dbProductService;
        }

        public IActionResult ViewProduct(int productId)
        {
            try
            {
                var userEmail = HttpContext.Session.GetString("Email");
                if (userEmail is not null)
                {
                    ViewBag.User = _dbUserService.Get(userEmail);
                }

                var model = _dbProductService.Get(productId);
                model.Comments = model.Comments.OrderByDescending(x => x.Id).ToList();
                return View(model);
            }
            catch
            {
                return Redirect("../Home/Index");
            }
        }
    }
}

Views/Home/GetAdditionalProducts.cshtml
@using SanTech.Models
@model IEnumerable<Product>
@{
    Layout = null;
}
    @foreach (Product u in Model)
    {
<div class="ads__content__item">
    <a asp-controller="ViewProduct" asp-action="ViewProduct" asp-route-productId="@u.Id">
        <div class="ads__content__item__image">
            <img src="data:image/jpeg;base64,@(Convert.ToBase64String(u.Image))" alt="">
        </div>
        <div class="text1 ads__content__item__title">
            @u.Title
        </div>
        <div class="text1 ads__content__item__code">Код: @u.Id</div>
        @if (u.IsNotAvailable)
        {
            <div class="text1 ads__content__item__notAvailable">Нет в наличии</div>
        }
        else if (u.SaleProcent == 0)
        {
            <div class="text1 ads__content__item__cost">@u.Cost.ToString("N0") грн.</div>
        }
        
        else
        {
            <div class="ads__content__item__sale">
                <div class="text1 item__sale__old">@u.Cost.ToString("N0") грн.</div>
                <div class="text1 item__sale__new">@{var saleCost = (u.Cost * (100 - u.SaleProcent)) / 100;}@saleCost.ToString("N0") грн.</div>
            </div>
        }
    </a>
    @if (!u.IsNotAvailable)
    {
        <div class="ads__content__item__basket" onclick="AddToBasket(@u.Id, '@ViewBag.User')">
            <svg width="70" height="70" viewBox="0 0 70 70" fill="none"
                 xmlns="http://www.w3.org/2000/svg">
                <path stroke="black" fill="black" fill-rule="evenodd" clip-rule="evenodd"
                      d="M2.91675 5.83337V11.6667H13.9511L17.1867 26.8887L17.1978 26.8864L18.5582 33.2883L18.5209 33.2961L22.0926 50.0993C19.4017 51.1721 17.5001 53.8015 17.5001 56.875C17.5001 60.9021 20.7647 64.1667 24.7917 64.1667C28.8188 64.1667 32.0834 60.9021 32.0834 56.875C32.0834 56.3757 32.0332 55.8881 31.9376 55.4167H49.7292C49.6336 55.8881 49.5834 56.3757 49.5834 56.875C49.5834 60.9021 52.848 64.1667 56.8751 64.1667C60.9021 64.1667 64.1667 60.9021 64.1667 56.875C64.1667 52.848 60.9021 49.5834 56.8751 49.5834H27.9466L26.7067 43.75H60.8855L67.0834 14.5834H20.5348L18.6959 5.93231V5.83337H2.91675ZM56.8751 55.4167C56.0698 55.4167 55.4167 56.0698 55.4167 56.875C55.4167 57.6803 56.0698 58.3334 56.8751 58.3334C57.6804 58.3334 58.3334 57.6803 58.3334 56.875C58.3334 56.0698 57.6804 55.4167 56.8751 55.4167ZM23.3334 56.875C23.3334 56.0698 23.9863 55.4167 24.7917 55.4167C25.5972 55.4167 26.2501 56.0698 26.2501 56.875C26.2501 57.6803 25.5972 58.3334 24.7917 58.3334C23.9863 58.3334 23.3334 57.6803 23.3334 56.875ZM21.7866 20.4167L25.5053 37.9167H56.1614L59.8801 20.4167H21.7866Z"
                      fill="#E7E7E7" />
            </svg>
        </div>
    }
    <div class="ads__content__item__like" onclick="AddToFavourites(@u.Id, '@ViewBag.User')">
        <svg width="40" height="40" viewBox="0 0 70 70" fill="none"
             xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M32.6904 16.7074L35.115 19.8633L37.3941 16.6006C41.8388 10.2374 48.8345 9.09819 54.6538 11.5013C60.5017 13.9164 64.9502 19.8392 64.0498 27.6634C63.5864 31.6933 61.6211 35.7503 58.7015 39.6651C55.7925 43.5656 52.0556 47.1633 48.3068 50.2491C44.5674 53.3273 40.8822 55.8421 38.1271 57.5892C36.8729 58.3843 35.8168 59.0169 35.0427 59.4681C34.2642 58.9909 33.1973 58.3207 31.9289 57.4816C29.168 55.6551 25.4749 53.0441 21.7266 49.8979C17.9682 46.7436 14.2204 43.1059 11.3016 39.2369C8.36501 35.3443 6.41437 31.4106 5.95383 27.6429C5.06378 20.3616 9.25707 14.4233 15.0171 11.8824C20.6891 9.38041 27.7261 10.2466 32.6904 16.7074Z"
                  fill="#000" />
        </svg>
    </div>
    @if (u.SaleProcent != 0 && !u.IsNotAvailable)
    {
        <div class="ads__content__item__saleInfo"><span class="text1">-@u.SaleProcent%</span></div>
    }
</div>
            }

Views/Home/LoadBasket.cshtml
@model IEnumerable<Basket>
@{
    Layout = null;
}
@if (ViewBag.User is not null)
{
    if (Model.Any())
    {
@foreach (Basket u in Model)
{
    <div class="basket__content__item" id="@u.Id">
        <div class="basket__content__item__first">
            <div class="basket__content__item__trash" onclick="DeleteFromBasket(@u.Id)">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="30px" height="30px"
                     viewBox="0 0 612.08 612.08" style="enable-background:new 0 0 612.08 612.08;"
                     xml:space="preserve">
                <g>
                <path d="M432,96h-48V32c0-17.672-14.328-32-32-32H160c-17.672,0-32,14.328-32,32v64H80c-17.672,0-32,14.328-32,32v32h416v-32
		C464,110.328,449.672,96,432,96z M192,96V64h128v32H192z" />
                <path d="M80,480.004C80,497.676,94.324,512,111.996,512h288.012C417.676,512,432,497.676,432,480.008v-0.004V192H80V480.004z
		 M320,272c0-8.836,7.164-16,16-16s16,7.164,16,16v160c0,8.836-7.164,16-16,16s-16-7.164-16-16V272z M240,272
		c0-8.836,7.164-16,16-16s16,7.164,16,16v160c0,8.836-7.164,16-16,16s-16-7.164-16-16V272z M160,272c0-8.836,7.164-16,16-16
		s16,7.164,16,16v160c0,8.836-7.164,16-16,16s-16-7.164-16-16V272z" />
                                </g>
                    </svg>
            </div>
            <div class="basket__content__item__image"><img src="data:image/jpeg;base64,@(Convert.ToBase64String(u.Product.Image))" alt=""></div>
            <div class="basket__content__item__info">
                <a asp-controller="ViewProduct" asp-action="ViewProduct" asp-route-productId="@u.Product.Id" class="text1 basket__content__item__info__title">
                    @u.Product.Title
                </a>
                <div class="text1 basket__content__item__info__cost">@{var saleCost = (u.Product.Cost * (100 - u.Product.SaleProcent)) / 100;}@saleCost.ToString("N0") грн.</div>

            </div>
        </div>
        <div class="basket__content__item__second">
            <div class="basket__content__item__amount">
               <div class="basket__content__item__amount__count number" data-step="1" data-min="1" data-max="100">
                    <div class="text1 amount__count__button number-minus">-</div>
                        <input name="count" value="@u.NumberOfProduct" type="number" id="@u.Id" class="text1 basket__content__item__amount__input">
                    <div class="text1 amount__count__button number-plus">+</div>
               </div>
                <div class="text1 basket__content__item__amount__cost">@{var totalCost = u.NumberOfProduct * saleCost;}@totalCost.ToString("N0") грн.</div>

</div>

</div>

</div>
}
                        <div class="basket__content__total">
                <div class="basket__content__total__info">
                    <div class="text2 basket__content__total__info__title">
                        Итог: <span class="basket__content__total__info__cost">@ViewBag.TotalCost.ToString("N0") грн.</span>
                    </div>
                    <a asp-controller="CreateOrder" asp-action="CreateOrder" class="button1 basket__content__total__info__button">
                        <div class="basket__content__total__info__button__basket">
                            <svg width="30" height="30" viewBox="0 0 70 70" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M2.91675 5.83337V11.6667H13.9511L17.1867 26.8887L17.1978 26.8864L18.5582 33.2883L18.5209 33.2961L22.0926 50.0993C19.4017 51.1721 17.5001 53.8015 17.5001 56.875C17.5001 60.9021 20.7647 64.1667 24.7917 64.1667C28.8188 64.1667 32.0834 60.9021 32.0834 56.875C32.0834 56.3757 32.0332 55.8881 31.9376 55.4167H49.7292C49.6336 55.8881 49.5834 56.3757 49.5834 56.875C49.5834 60.9021 52.848 64.1667 56.8751 64.1667C60.9021 64.1667 64.1667 60.9021 64.1667 56.875C64.1667 52.848 60.9021 49.5834 56.8751 49.5834H27.9466L26.7067 43.75H60.8855L67.0834 14.5834H20.5348L18.6959 5.93231V5.83337H2.91675ZM56.8751 55.4167C56.0698 55.4167 55.4167 56.0698 55.4167 56.875C55.4167 57.6803 56.0698 58.3334 56.8751 58.3334C57.6804 58.3334 58.3334 57.6803 58.3334 56.875C58.3334 56.0698 57.6804 55.4167 56.8751 55.4167ZM23.3334 56.875C23.3334 56.0698 23.9863 55.4167 24.7917 55.4167C25.5972 55.4167 26.2501 56.0698 26.2501 56.875C26.2501 57.6803 25.5972 58.3334 24.7917 58.3334C23.9863 58.3334 23.3334 57.6803 23.3334 56.875ZM21.7866 20.4167L25.5053 37.9167H56.1614L59.8801 20.4167H21.7866Z"
                                      fill="#000" />
                            </svg>
                        </div>
                        <span class="text1 basket__content__total__info__button__text">Оформить заказ</span>
                    </a>
                </div>
            </div>
    }
    else
    {
    <div class="basket__content__orders__error">
        <div class="text2 basket__content__orders__error__text">Корзина пустая</div>
    </div>
    }
}
else
{
    <div class="basket__content__orders__error">
        <div class="text2 basket__content__orders__error__text">Вы не авторизованы</div>
        <a asp-action="SignInAccount" asp-controller="SignInAccount" class="text1 button1 basket__content__orders__error__button"><span>Войти</span></a>
    </div>
}

Views/Home/LoadBySearch.cshtml
@foreach (Product u in Model)
{
    <div class="ads__content__item">
        <a asp-controller="ViewProduct" asp-action="ViewProduct" asp-route-productId="@u.Id">
            <div class="ads__content__item__image">
                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(u.Image))" alt="">
            </div>
            <div class="text1 ads__content__item__title">
                @u.Title
            </div>
            <div class="text1 ads__content__item__code">Код: @u.Id</div>
            @if (u.SaleProcent == 0)
            {
                <div class="text1 ads__content__item__cost">@u.Cost.ToString("N0") грн.</div>
            }
            else
            {
                <div class="ads__content__item__sale">
                    <div class="text1 item__sale__old">@u.Cost.ToString("N0") грн.</div>
                    <div class="text1 item__sale__new">@{var saleCost = (u.Cost * (100 - u.SaleProcent)) / 100;}@saleCost.ToString("N0") грн.</div>
                </div>
            }
        </a>
        <div class="ads__content__item__basket" onclick="AddToBasket(@u.Id, '@ViewBag.User')">
            <svg width="70" height="70" viewBox="0 0 70 70" fill="none"
                 xmlns="http://www.w3.org/2000/svg">
                <path stroke="black" fill="black" fill-rule="evenodd" clip-rule="evenodd"
                      d="M2.91675 5.83337V11.6667H13.9511L17.1867 26.8887L17.1978 26.8864L18.5582 33.2883L18.5209 33.2961L22.0926 50.0993C19.4017 51.1721 17.5001 53.8015 17.5001 56.875C17.5001 60.9021 20.7647 64.1667 24.7917 64.1667C28.8188 64.1667 32.0834 60.9021 32.0834 56.875C32.0834 56.3757 32.0332 55.8881 31.9376 55.4167H49.7292C49.6336 55.8881 49.5834 56.3757 49.5834 56.875C49.5834 60.9021 52.848 64.1667 56.8751 64.1667C60.9021 64.1667 64.1667 60.9021 64.1667 56.875C64.1667 52.848 60.9021 49.5834 56.8751 49.5834H27.9466L26.7067 43.75H60.8855L67.0834 14.5834H20.5348L18.6959 5.93231V5.83337H2.91675ZM56.8751 55.4167C56.0698 55.4167 55.4167 56.0698 55.4167 56.875C55.4167 57.6803 56.0698 58.3334 56.8751 58.3334C57.6804 58.3334 58.3334 57.6803 58.3334 56.875C58.3334 56.0698 57.6804 55.4167 56.8751 55.4167ZM23.3334 56.875C23.3334 56.0698 23.9863 55.4167 24.7917 55.4167C25.5972 55.4167 26.2501 56.0698 26.2501 56.875C26.2501 57.6803 25.5972 58.3334 24.7917 58.3334C23.9863 58.3334 23.3334 57.6803 23.3334 56.875ZM21.7866 20.4167L25.5053 37.9167H56.1614L59.8801 20.4167H21.7866Z"
                      fill="#E7E7E7" />
            </svg>
        </div>
        <div class="ads__content__item__like">
            <svg width="40" height="40" viewBox="0 0 70 70" fill="none"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd"
                      d="M32.6904 16.7074L35.115 19.8633L37.3941 16.6006C41.8388 10.2374 48.8345 9.09819 54.6538 11.5013C60.5017 13.9164 64.9502 19.8392 64.0498 27.6634C63.5864 31.6933 61.6211 35.7503 58.7015 39.6651C55.7925 43.5656 52.0556 47.1633 48.3068 50.2491C44.5674 53.3273 40.8822 55.8421 38.1271 57.5892C36.8729 58.3843 35.8168 59.0169 35.0427 59.4681C34.2642 58.9909 33.1973 58.3207 31.9289 57.4816C29.168 55.6551 25.4749 53.0441 21.7266 49.8979C17.9682 46.7436 14.2204 43.1059 11.3016 39.2369C8.36501 35.3443 6.41437 31.4106 5.95383 27.6429C5.06378 20.3616 9.25707 14.4233 15.0171 11.8824C20.6891 9.38041 27.7261 10.2466 32.6904 16.7074Z"
                      fill="#000" />
            </svg>
        </div>
        @if (u.SaleProcent != 0)
        {
            <div class="ads__content__item__saleInfo"><span class="text1">-@u.SaleProcent%</span></div>
        }
    </div>
}

Views/Home/LoadFavorites.cshtml
@model IEnumerable<Favorite>
@{
    Layout = null;
}
@if (ViewBag.User is not null)
{
    if (Model.Any())
    {
        @foreach (Favorite u in Model)
        {
            <div class="favourites__content__item">
                <div class="favourites__content__item__first">
                    <div class="favourites__content__item__trash" onclick="DeleteFromFavorites(@u.Id)">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                             x="0px" y="0px" width="30px" height="30px" viewBox="0 0 612.08 612.08"
                             style="enable-background:new 0 0 612.08 612.08;" xml:space="preserve">
                        <g>
                        <path d="M432,96h-48V32c0-17.672-14.328-32-32-32H160c-17.672,0-32,14.328-32,32v64H80c-17.672,0-32,14.328-32,32v32h416v-32
    		C464,110.328,449.672,96,432,96z M192,96V64h128v32H192z" />
                        <path d="M80,480.004C80,497.676,94.324,512,111.996,512h288.012C417.676,512,432,497.676,432,480.008v-0.004V192H80V480.004z
    		 M320,272c0-8.836,7.164-16,16-16s16,7.164,16,16v160c0,8.836-7.164,16-16,16s-16-7.164-16-16V272z M240,272
    		c0-8.836,7.164-16,16-16s16,7.164,16,16v160c0,8.836-7.164,16-16,16s-16-7.164-16-16V272z M160,272c0-8.836,7.164-16,16-16
    		s16,7.164,16,16v160c0,8.836-7.164,16-16,16s-16-7.164-16-16V272z" />
                                </g>
                    </div>
                    <div class="favourites__content__item__image"><img src="data:image/jpeg;base64,@(Convert.ToBase64String(u.Product.Image))" alt=""></div>
                    <div class="favourites__content__item__info">
                        <a asp-controller="ViewProduct" asp-action="ViewProduct" asp-route-productId="@u.Product.Id" class="text1 favourites__content__item__info__title">
                            @u.Product.Title
                        </a>
                        <div class="text1 favourites__content__item__info__cost">@{var saleCost = (u.Product.Cost * (100 - u.Product.SaleProcent)) / 100;}@saleCost.ToString("N0") грн.</div>

                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div class="basket__content__orders__error">
            <div class="text2 basket__content__orders__error__text">У нету избранных товаров</div>
        </div>
    }
}
else
{
    <div class="basket__content__orders__error">
        <div class="text2 basket__content__orders__error__text">Вы не авторизованы</div>
        <a asp-action="SignInAccount" asp-controller="SignInAccount" class="text1 button1 basket__content__orders__error__button"><span>Войти</span></a>
    </div>
}

Views/Home/RedactProfile.cshtml
@model SanTech.Models.User
@{ 
    Layout = "_Layout";
}
<link href="~/css/profileRedact.css" rel="stylesheet" />
<div class="redact">
    <form asp-controller="Home" asp-action="RedactProfile" method="post" enctype="multipart/form-data">
        <div class="text2 redact__title">Редактирование продукта</div>
        <div class="redact__content">
            <div class="redact__content__flex__image">
                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(ViewBag.User.Avatar))" alt="">
            </div>
            <div class="redact__content__flex__newImage">
                <label for="myfile" class="text1 chous">Выберите фотографию</label>
                <input type="file" class="my" id="myfile" name="UploadedFile" />
            </div>
            <p class="text1 text__under__input">Имя</p>
            <div class="text1 redact__content__flex__title"><input type="text" asp-for="Name" value="@ViewBag.User.Name"></div>
            <p class="text1 text__under__input">Phone</p>
            <div class="text1 redact__content__flex__saleProcent"><input type="tel" asp-for="Phone" value="@ViewBag.User.Phone"></div>
            <p class="text1 text__under__input">Введите пароль, если хотите его сменить</p>
            <div class="text1 redact__content__flex__saleProcent"><input type="password" asp-for="Password" value=""></div>
            <p class="text1 text__under__input">Повторите пароль</p>
            <div class="text1 redact__content__flex__saleProcent"><input type="password" asp-for="PasswordConfirm" value=""></div>
        </div>
        <button type="submit" class="text1 button1 redact__content__button">Редактировать</button>
    </form>
</div>

Views/Home/UpdateUser.cshtml
@model SanTech.Models.User
@{ 
    Layout = "_Layout";
}
<link href="~/css/profileRedact.css" rel="stylesheet" />
<div class="redact">
    <form asp-controller="Home" asp-action="UpdateUser" method="post" enctype="multipart/form-data">
        <div class="text2 redact__title">Редактирование профиля</div>
        <div class="redact__content">
            <div class="redact__content__flex__image">
                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(ViewBag.User.Avatar))" alt="">
            </div>
            <div class="redact__content__flex__newImage">
                <label for="myfile" class="text1 chous">Выберите фотографию</label>
                <input type="file" class="my" id="myfile" name="UploadedFile" />
            </div>
            <p class="text1 text__under__input">Имя</p>
            <div class="text1 redact__content__flex__title"><input type="text" asp-for="Name" value="@ViewBag.User.Name"></div>
            <p class="text1 text__under__input">Phone</p>
            <div class="text1 redact__content__flex__saleProcent"><input type="tel" asp-for="Phone" value="@ViewBag.User.Phone"></div>
            <p class="text1 text__under__input">Введите пароль, если хотите его сменить</p>
            <div class="text1 redact__content__flex__saleProcent"><input type="password" asp-for="Password" value=""></div>
            <p class="text1 text__under__input">Повторите пароль</p>
            <div class="text1 redact__content__flex__saleProcent"><input type="password" asp-for="PasswordConfirm" value=""></div>
        </div>
        <button type="submit" class="text1 button1 redact__content__button">Редактировать</button>
    </form>
</div>